"""Does TRL's colocate weight sync survive the sleep-mode reload?

TRL pushes the merged policy into vLLM with sync_weights(), then calls generate(), which under
enable_sleep_mode does wake_up() followed by collective_rpc("reload_weights"). vLLM's
reload_weights re-reads the model from its original checkpoint, so if it runs after the sync the
rollouts come from the BASE model, not the policy being trained.

This reproduces that exact sequence and reads the weights back out of the worker.
"""
from __future__ import annotations

import os
import sys

import torch
from vllm import LLM

MODEL = sys.argv[1] if len(sys.argv) > 1 else "google/gemma-4-E2B-it"
PARAM = "model.language_model.layers.0.self_attn.q_proj.weight"


def _pick(params):
    """Deterministically choose one large attention weight, whatever the naming scheme."""
    for pat in ("layers.0.self_attn.qkv_proj.weight", "layers.0.self_attn.q_proj.weight",
                "layers.0.self_attn.o_proj.weight"):
        for k in params:
            if k.endswith(pat) or pat in k:
                return k
    cands = [k for k in params if params[k].dim() == 2 and params[k].numel() > 100_000]
    return sorted(cands)[0] if cands else sorted(params)[0]


def _probe(worker, name):
    """Return (found_name, float64 sum) for a parameter inside the vLLM worker's model."""
    params = dict(worker.model_runner.model.named_parameters())
    if name not in params:
        name = _pick(params)
    return (name, float(params[name].detach().float().sum().item()))


def _perturb(worker, name):
    """Simulate sync_weights(): write a distinctly different value into the model."""
    params = dict(worker.model_runner.model.named_parameters())
    if name not in params:
        name = _pick(params)
    with torch.no_grad():
        params[name].add_(1.0)  # unmistakable, uniform shift
    return float(params[name].detach().float().sum().item())


llm = LLM(
    model=MODEL,
    enable_sleep_mode=True,
    max_model_len=4096,
    gpu_memory_utilization=0.35,
    enforce_eager=True,
)

name, base = llm.collective_rpc(_probe, args=(PARAM,))[0]
print(f"[probe] parameter: {name}")
print(f"[1] base checkpoint sum          = {base:.6f}")

after_write = llm.collective_rpc(_perturb, args=(PARAM,))[0]
print(f"[2] after simulated sync_weights = {after_write:.6f}   (delta {after_write - base:+.1f})")

_, verify = llm.collective_rpc(_probe, args=(PARAM,))[0]
print(f"[3] read back before reload      = {verify:.6f}")

# Split the two effects apart. First: does sleep/wake ALONE lose the synced weights?
llm.sleep(level=1)
llm.wake_up(tags=["weights"])
_, after_wake = llm.collective_rpc(_probe, args=(PARAM,))[0]
print(f"[4a] after sleep+wake, NO reload   = {after_wake:.6f}")
print("     -> sleep/wake alone " + ("LOSES" if abs(after_wake-base)<1e-3 else "PRESERVES") + " the synced weights")

# Then: the reload_weights call TRL adds on top.
try:
    llm.collective_rpc("reload_weights")
    reload_ran = True
except NotImplementedError:
    reload_ran = False
print(f"[4b] collective_rpc('reload_weights') executed: {reload_ran}")

_, after_reload = llm.collective_rpc(_probe, args=(PARAM,))[0]
print(f"[5] after wake_up + reload       = {after_reload:.6f}")

print()
if abs(after_reload - base) < 1e-3 and abs(after_write - base) > 1e-3:
    print(">>> VERDICT: synced weights were DISCARDED. vLLM is back on the base checkpoint.")
    print(">>> Rollouts under enable_sleep_mode=True are generated by the BASE model.")
elif abs(after_reload - after_write) < 1e-3:
    print(">>> VERDICT: synced weights SURVIVED the reload. Sleep mode is not the culprit.")
else:
    print(">>> VERDICT: inconclusive — weights match neither base nor the written value.")
